package {
    location: "<a href='http://coapp.org/repository/${OutputFilename}'>http://coapp.org/repository/${OutputFilename}</a>";
    feed: "<a href='http://coapp.org/repository/packages.atom.xml'>http://coapp.org/repository/packages.atom.xml</a>";
    publisher: "Outercurve Foundation, CoApp Project";
}

identity[CoApp Project] {
    name : "CoApp Project, Outercurve Foundation";
    email: "<a href='mailto:coapp@coapp.org'>coapp@coapp.org</a>";
    website: "<a href='http://coapp.org'>http://coapp.org</a>";
}
